//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.16 at 12:05:38 AM EEST 
//


package org.example.entity.orders;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the hlova.stanislav.shoe_shop.orders package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hlova.stanislav.shoe_shop.orders
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Orders }
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link Order }
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link OrderItems }
     */
    public OrderItems createOrderItems() {
        return new OrderItems();
    }

    /**
     * Create an instance of {@link OrderItem }
     */
    public OrderItem createOrderItem() {
        return new OrderItem();
    }

    /**
     * Create an instance of {@link Count }
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link Discount }
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link Total }
     */
    public Total createTotal() {
        return new Total();
    }

    /**
     * Create an instance of {@link Buyer }
     */
    public Buyer createBuyer() {
        return new Buyer();
    }

    /**
     * Create an instance of {@link Contact }
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link Receiver }
     */
    public Receiver createReceiver() {
        return new Receiver();
    }

    /**
     * Create an instance of {@link Delivery }
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

}
