//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.16 at 12:05:38 AM EEST 
//


package org.example.entity.orders;

import org.example.entity.CurrencyType;

import java.math.BigDecimal;


public class Discount extends CurrencyType {


    public Discount() {
    }

    public Discount(BigDecimal value, String currency) {
        super(value, currency);
    }
}
