//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.16 at 12:05:38 AM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://stanislav.hlova/shoe-shop")
package org.example.entity;
