//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.10.16 at 12:05:38 AM EEST 
//


package org.example.entity.orders;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonSerializer;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

import java.io.IOException;
import java.util.Arrays;


/**
 * <p>Java class for OrderStatus.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="OrderStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Очікує розгляду"/&gt;
 *     &lt;enumeration value="Підтверджено"/&gt;
 *     &lt;enumeration value="Відхилено"/&gt;
 *     &lt;enumeration value="Скасовано"/&gt;
 *     &lt;enumeration value="Виконано"/&gt;
 *     &lt;enumeration value="В обробці"/&gt;
 *     &lt;enumeration value="На доставці"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "OrderStatus")
@XmlEnum
@JsonSerialize(using = OrderStatus.OrderStatusSerializer.class)
@JsonDeserialize(using = OrderStatus.OrderStatusDeserializer.class)
public enum OrderStatus {

    @XmlEnumValue("Очікує розгляд")
    WAIT_FOR_CONSIDERATION("Очікує розгляд"),
    @XmlEnumValue("Підтверджено")
    ACCEPTED("Підтверджено"),
    @XmlEnumValue("Відхилено")
    DECLINED("Відхилено"),
    @XmlEnumValue("Скасовано")
    CANCELLED("Скасовано"),
    @XmlEnumValue("Виконано")
    DONE("Виконано"),
    @XmlEnumValue("В обробці")
    IN_PROCESS("В обробці"),
    @XmlEnumValue("На доставці")
    ON_DELIVERY("На доставці");
    private final String value;

    OrderStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OrderStatus fromValue(String v) {
        for (OrderStatus c : OrderStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    public static class OrderStatusDeserializer extends JsonDeserializer<OrderStatus> {
        public OrderStatusDeserializer() {
        }

        @Override
        public OrderStatus deserialize(JsonParser p, DeserializationContext ctxt) throws IOException {
            String value = p.getText();
            try {
                return OrderStatus.fromValue(value);
            } catch (IllegalArgumentException e) {
                String validValues = String.join(", ",
                        Arrays.stream(OrderStatus.values())
                                .map(OrderStatus::value)
                                .toArray(String[]::new)
                );
                throw new IOException("Invalid value for OrderStatus: '" + value + "'. Valid values are: " + validValues);
            }
        }
    }
    public static class OrderStatusSerializer extends JsonSerializer<OrderStatus> {
        @Override
        public void serialize(OrderStatus orderStatus, JsonGenerator gen, SerializerProvider serializers) throws IOException {
            gen.writeString(orderStatus.value());
        }
    }
}
