
package hlova.stanislav.shoe_shop.service.orders;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "Orders", targetNamespace = "http://stanislav.hlova/shoe-shop/service/orders", wsdlLocation = "http://localhost:9000/orders?wsdl")
public class Orders
    extends Service
{

    private final static URL ORDERS_WSDL_LOCATION;
    private final static WebServiceException ORDERS_EXCEPTION;
    private final static QName ORDERS_QNAME = new QName("http://stanislav.hlova/shoe-shop/service/orders", "Orders");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/orders?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERS_WSDL_LOCATION = url;
        ORDERS_EXCEPTION = e;
    }

    public Orders() {
        super(__getWsdlLocation(), ORDERS_QNAME);
    }

    public Orders(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERS_QNAME, features);
    }

    public Orders(URL wsdlLocation) {
        super(wsdlLocation, ORDERS_QNAME);
    }

    public Orders(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERS_QNAME, features);
    }

    public Orders(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Orders(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderPort")
    public OrderService getOrderPort() {
        return super.getPort(new QName("http://stanislav.hlova/shoe-shop/service/orders", "OrderPort"), OrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderService
     */
    @WebEndpoint(name = "OrderPort")
    public OrderService getOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://stanislav.hlova/shoe-shop/service/orders", "OrderPort"), OrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERS_EXCEPTION!= null) {
            throw ORDERS_EXCEPTION;
        }
        return ORDERS_WSDL_LOCATION;
    }

}
